nodename = "gomq"
datadir = "./data"

[tcp]
enable = true
port = 1883
proxy_protocol = false

[ssl]
enable = true
port = 8883
proxy_protocol = true
tlscert = "./cert/gomq.crt"
tlskey = "./cert/gomq.key"

[ws]
enable = true
port = 8083
proxy_protocol = true
path = "/mqtt"

[wss]
enable = true
port = 8084
proxy_protocol = true
path = "/mqtt"
tlscert = "./cert/gomq.crt"
tlskey = "./cert/gomq.key"

[store]
type = "ram"

[api]
port = 8421

[mqtt]
retain_available = true
max_topic_alias = 65535
session_expiry_interval = 60
max_receive = 128
max_inflight = 32
server_keep_alive = 0
max_packet_size = 10240
max_qos = 2
wildcard_sub = true
sub_id = true
shared_sub = true

[cluster]
port = 8422
discovery = "static"
nodes = ["192.168.0.6:8422","192.168.0.7:8422"]

[log]
level = "info"
format = "json"
maxage = 7
maxsize = 10
maxcount = 10
