datadir = "/Users/laomar/Documents/Project/gomq/data"

[tcp]
enable = true
port = 1883

[ssl]
enable = true
port = 8883
tlscert = "/Users/laomar/Documents/Project/gomq/data/cert/gomq.crt"
tlskey = "/Users/laomar/Documents/Project/gomq/data/cert/gomq.key"

[ws]
enable = true
port = 8083
path = "/mqtt"

[wss]
enable = true
port = 8084
path = "/mqtt"
tlscert = "/Users/laomar/Documents/Project/gomq/data/cert/gomq.crt"
tlskey = "/Users/laomar/Documents/Project/gomq/data/cert/gomq.key"

[api]
port = 8421

[mqtt]

[node]


[cluster]
name = "gomq@127.0.0.1"
port = 8422
discovery = "static"
nodes = ["gomq1@127.0.0.1","gomq2@127.0.0.1"]

[log]
level = "debug"
format = "text"
maxage = 7
maxsize = 10
maxcount = 10
