datadir = "./data/node3"

[tcp]
enable = true
port = 1885

[ws]
enable = true
port = 8085
path = "/mqtt"

[api]
port = 8268

[cluster]
node_name = "node3"
grpc_port = 8868
gossip_port = 8668
retry_join = ["127.0.0.1:8666", "127.0.0.1:8667", "127.0.0.1:8668"]
retry_interval = 5
retry_timeout = 30
rejoin_after_leave = true
