datadir = "./data/node1"

[tcp]
enable = true
port = 1883

[ws]
enable = true
port = 8083
path = "/mqtt"

[api]
port = 8266

[cluster]
node_name = "node1"
grpc_port = 8866
gossip_port = 8666
retry_join = ["127.0.0.1:8666", "127.0.0.1:8667", "127.0.0.1:8668"]
retry_interval = 5
retry_timeout = 30
rejoin_after_leave = true

[log]
level = "debug"